### ISSUE TITLE
ModuleManagement cannot handle '74' modules.The limit is 63.

### ISSUE THREAD

**Issue by seadba** [AndiBellstedt/PackageUpdateInfo#11]
looks very useful thanks - have you seen this

S C:\projects\scripts> Get-PackageUpdateInfo
PackageManagement\Find-Package : ModuleManagement cannot handle '74' modules.The limit is 63.

**Comment by AndiBellstedt** [comment]
Hi. Thanks for the interest.
No, can't say… what is the problem, without some details about your system.
What is the version you are running on? Windows / Linux / 5.x / 6 ?

Do you have multiple Repositories installed? (individual Repos additional to the PSGallery?)
--> Get-PSRepository?

Can you Provide a list of your modules installed? (UserScope, AllUsers)

**Comment by seadba** [comment]
thanks
1.windows
Name                           Value
----                           -----
PSVersion                      5.1.17134.407

2.  PS C:\WINDOWS\system32> Get-PSRepository

Name                      InstallationPolicy   SourceLocation
----                      ------------------   --------------
PSGallery                 Trusted              https://www.powershellgallery.com/api/v2

3. PS C:\WINDOWS\system32> $(get-installedModule).count
72

PS C:\WINDOWS\system32> get-installedmodule | select Name

Name
----
aws-toolbox
AWSExt
AWSPowerShell
Az
Az.Accounts
Az.Aks
Az.AnalysisServices
Az.ApiManagement
Az.ApplicationInsights
Az.Automation
Az.Batch
Az.Billing
Az.Cdn
Az.CognitiveServices
Az.Compute
Az.ContainerInstance
Az.ContainerRegistry
Az.DataFactory
Az.DataLakeAnalytics
Az.DataLakeStore
Az.DevTestLabs
Az.Dns
Az.EventGrid
Az.EventHub
Az.HDInsight
Az.IotHub
Az.KeyVault
Az.LogicApp
Az.MachineLearning
Az.MarketplaceOrdering
Az.Media
Az.Monitor
Az.Network
Az.NotificationHubs
Az.OperationalInsights
Az.PolicyInsights
Az.PowerBIEmbedded
Az.RecoveryServices
Az.RedisCache
Az.Relay
Az.Resources
Az.ServiceBus
Az.ServiceFabric
Az.SignalR
Az.Sql
Az.Storage
Az.StreamAnalytics
Az.TrafficManager
Az.Websites
BAMCIS.Common
BAMCIS.Logging
BurntToast
dbachecks
dbatools
EditorServicesComma...
ExcelPSLib
ImportExcel
InvokeBuild
MicrosoftPowerBIMgmt
MicrosoftPowerBIMgm...
MicrosoftPowerBIMgm...
MicrosoftPowerBIMgm...
MicrosoftPowerBIMgm...
PackageManagement
PackageUpdateInfo
Pester
PowerShellExplorer
PowerShellGet
PSFramework
PSStringTemplate
SqlServer
UniversalDashboard...

**Comment by AndiBellstedt** [comment]
I think a had it. Find-Module only accept a maximum number of 63 names on  parameter name.
I've wrapped a loop arround that one. #11 fixed in #Version 1.1.1.0

**Comment by seadba** [comment]
looks good - thanks for the fast response

PS C:\projects\scripts\ps> Get-PackageUpdateInfo

Name                            Repository VersionInstalled VersionOnline NeedUpdate HasReleaseNotes PublishedDate         Path
----                            ---------- ---------------- ------------- ---------- --------------- -------------         ----
UniversalDashboard.Community    PSGallery  2.0.1            2.3.0         True       True            2/11/2019 9:15:34 AM  C:\Program Files\WindowsPowerShell\Modules\UniversalDashboard.Community
SqlServer                       PSGallery  21.1.18080       21.1.18080    False      True            1/31/2019 6:42:05 AM  C:\Program Files\WindowsPowerShell\Modules\SqlServer
PSStringTemplate                PSGallery  0.2.0            0.2.0         False      True            11/11/2017 6:53:13 PM C:\Program Files\WindowsPowerShell\Modules\PSStringTemplate
PSScriptAnalyzer                PSGallery  1.17.1           1.17.1        False      True            6/5/2018 9:32:49 PM   C:\projects\scripts\PowerShellEditorServices\module\PSScriptAnalyzer

**Comment by AndiBellstedt** [comment]
I'll suggest to try the switch parameter '-showToastNotification'... It's way more fun with that one.
Take a look on the Readme in the GitHub. 😀

**Comment by AndiBellstedt** [comment]
But anyway... Happy to solve the problem.
