### ISSUE TITLE
Module version number 1.9 is higher than 1.10

### ISSUE THREAD

**Issue by tbone4711** [AndiBellstedt/PackageUpdateInfo#24]
Actual I get a warning (PackageUpdateInfo 1.2.1.0)
WARNING: Local version for module 'Az.CognitiveServices' is higher than online version: local v1.9.0 <-- v1.10.0 online
which seems a little bit strange to me. 
Version              Name                                Repository           Description
1.9.0                Az.CognitiveServices                PSGallery            Microsoft Azure PowerShell - Cognitive [...]

All other version are displayed correct. 
4.1.0 -> 4.1.1
4.13.0 -> 4.14.0

**Comment by AndiBellstedt** [comment]
Hi, sorry for ignoring your issue so long. (I assume the information mail from github was eaten by spam detection.)

Actually, the situation sound very strange.
I wasn't able to reproduce.
Did a check on the source code.... have no glue what is causing this situation.

Is the issue still present?

**Comment by tbone4711** [comment]
It's still a problem (1.2.3.0):
`Get-PackageUpdateInfo -ShowOnlyNeededUpdate -Force

WARNING: Local version for module 'Az' is higher than online version: local v9.7.1 <-- v10.3.0 online

WARNING: Local version for module 'Az.KeyVault' is higher than online version: local v4.9.3 <-- v4.11.0 online

WARNING: Local version for module 'Az.Resources' is higher than online version: local v6.6.1 <-- v6.10.0 online

WARNING: Local version for module 'Az.Sql' is higher than online version: local v4.6.0 <-- v4.10.0 online

WARNING: Local version for module 'Az.Storage' is higher than online version: local v5.6.0 <-- v5.10.0 online`

**Comment by AndiBellstedt** [comment]
Can you tell me something about your environment, please.

Are you on Windows or Linux?
What is your PSVersion?

**Comment by AndiBellstedt** [comment]
Think, I found the issue.  Will be fixed in version 1.2.4.0 (, hopefully ^^).
